
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2017 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
* Use of the Software is limited solely to applications:
*(a) running on a Xilinx device, or
*(b) that interact with a Xilinx device through a bus or interconnect.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*XILINX BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_GPIO_0_DEVICE_ID,
		XPAR_AXI_GPIO_0_BASEADDR,
		XPAR_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_1_DEVICE_ID,
		XPAR_AXI_GPIO_1_BASEADDR,
		XPAR_AXI_GPIO_1_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_1_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_10_DEVICE_ID,
		XPAR_AXI_GPIO_10_BASEADDR,
		XPAR_AXI_GPIO_10_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_10_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_11_DEVICE_ID,
		XPAR_AXI_GPIO_11_BASEADDR,
		XPAR_AXI_GPIO_11_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_11_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_12_DEVICE_ID,
		XPAR_AXI_GPIO_12_BASEADDR,
		XPAR_AXI_GPIO_12_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_12_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_13_DEVICE_ID,
		XPAR_AXI_GPIO_13_BASEADDR,
		XPAR_AXI_GPIO_13_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_13_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_14_DEVICE_ID,
		XPAR_AXI_GPIO_14_BASEADDR,
		XPAR_AXI_GPIO_14_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_14_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_15_DEVICE_ID,
		XPAR_AXI_GPIO_15_BASEADDR,
		XPAR_AXI_GPIO_15_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_15_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_16_DEVICE_ID,
		XPAR_AXI_GPIO_16_BASEADDR,
		XPAR_AXI_GPIO_16_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_16_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_17_DEVICE_ID,
		XPAR_AXI_GPIO_17_BASEADDR,
		XPAR_AXI_GPIO_17_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_17_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_18_DEVICE_ID,
		XPAR_AXI_GPIO_18_BASEADDR,
		XPAR_AXI_GPIO_18_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_18_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_19_DEVICE_ID,
		XPAR_AXI_GPIO_19_BASEADDR,
		XPAR_AXI_GPIO_19_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_19_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_2_DEVICE_ID,
		XPAR_AXI_GPIO_2_BASEADDR,
		XPAR_AXI_GPIO_2_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_2_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_3_DEVICE_ID,
		XPAR_AXI_GPIO_3_BASEADDR,
		XPAR_AXI_GPIO_3_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_3_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_4_DEVICE_ID,
		XPAR_AXI_GPIO_4_BASEADDR,
		XPAR_AXI_GPIO_4_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_4_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_5_DEVICE_ID,
		XPAR_AXI_GPIO_5_BASEADDR,
		XPAR_AXI_GPIO_5_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_5_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_6_DEVICE_ID,
		XPAR_AXI_GPIO_6_BASEADDR,
		XPAR_AXI_GPIO_6_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_6_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_7_DEVICE_ID,
		XPAR_AXI_GPIO_7_BASEADDR,
		XPAR_AXI_GPIO_7_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_7_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_8_DEVICE_ID,
		XPAR_AXI_GPIO_8_BASEADDR,
		XPAR_AXI_GPIO_8_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_8_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_9_DEVICE_ID,
		XPAR_AXI_GPIO_9_BASEADDR,
		XPAR_AXI_GPIO_9_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_9_IS_DUAL
	}
};


